/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyIndexRouteImport } from './routes/company.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentMerciRouteImport } from './routes/student.merci'
import { Route as StudentConventionRouteImport } from './routes/student.convention'
import { Route as StudentTokenRouteImport } from './routes/student.$token'
import { Route as CompanyTokenRouteImport } from './routes/company.$token'
import { Route as AdminValidationsRouteImport } from './routes/admin.validations'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminRuptureRouteImport } from './routes/admin.rupture'
import { Route as AdminMergedRouteImport } from './routes/admin.merged'
import { Route as AdminLinksRouteImport } from './routes/admin.links'
import { Route as AdminFormLogRouteImport } from './routes/admin.form-log'
import { Route as AdminFeuilleSuiviRouteImport } from './routes/admin.feuille-suivi'
import { Route as AdminConventionTrackingRouteImport } from './routes/admin.convention-tracking'
import { Route as AdminConventionRouteImport } from './routes/admin.convention'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'
import { Route as AdminAttestationRouteImport } from './routes/admin.attestation'
import { Route as AdminCompaniesIndexRouteImport } from './routes/admin.companies.index'
import { Route as AdminValidationsIdRouteImport } from './routes/admin.validations.$id'
import { Route as AdminCompaniesIdRouteImport } from './routes/admin.companies.$id'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanyRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentMerciRoute = StudentMerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => StudentRoute,
} as any)
const StudentConventionRoute = StudentConventionRouteImport.update({
  id: '/convention',
  path: '/convention',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTokenRoute = StudentTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => StudentRoute,
} as any)
const CompanyTokenRoute = CompanyTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => CompanyRoute,
} as any)
const AdminValidationsRoute = AdminValidationsRouteImport.update({
  id: '/validations',
  path: '/validations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRuptureRoute = AdminRuptureRouteImport.update({
  id: '/rupture',
  path: '/rupture',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMergedRoute = AdminMergedRouteImport.update({
  id: '/merged',
  path: '/merged',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormLogRoute = AdminFormLogRouteImport.update({
  id: '/form-log',
  path: '/form-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeuilleSuiviRoute = AdminFeuilleSuiviRouteImport.update({
  id: '/feuille-suivi',
  path: '/feuille-suivi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConventionTrackingRoute = AdminConventionTrackingRouteImport.update({
  id: '/convention-tracking',
  path: '/convention-tracking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConventionRoute = AdminConventionRouteImport.update({
  id: '/convention',
  path: '/convention',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttestationRoute = AdminAttestationRouteImport.update({
  id: '/attestation',
  path: '/attestation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesIndexRoute = AdminCompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCompaniesRoute,
} as any)
const AdminValidationsIdRoute = AdminValidationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminValidationsRoute,
} as any)
const AdminCompaniesIdRoute = AdminCompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCompaniesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/company': typeof CompanyRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/admin/attestation': typeof AdminAttestationRoute
  '/admin/companies': typeof AdminCompaniesRouteWithChildren
  '/admin/convention': typeof AdminConventionRoute
  '/admin/convention-tracking': typeof AdminConventionTrackingRoute
  '/admin/feuille-suivi': typeof AdminFeuilleSuiviRoute
  '/admin/form-log': typeof AdminFormLogRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/merged': typeof AdminMergedRoute
  '/admin/rupture': typeof AdminRuptureRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/validations': typeof AdminValidationsRouteWithChildren
  '/company/$token': typeof CompanyTokenRoute
  '/student/$token': typeof StudentTokenRoute
  '/student/convention': typeof StudentConventionRoute
  '/student/merci': typeof StudentMerciRoute
  '/admin/': typeof AdminIndexRoute
  '/company/': typeof CompanyIndexRoute
  '/admin/companies/$id': typeof AdminCompaniesIdRoute
  '/admin/validations/$id': typeof AdminValidationsIdRoute
  '/admin/companies/': typeof AdminCompaniesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/attestation': typeof AdminAttestationRoute
  '/admin/convention': typeof AdminConventionRoute
  '/admin/convention-tracking': typeof AdminConventionTrackingRoute
  '/admin/feuille-suivi': typeof AdminFeuilleSuiviRoute
  '/admin/form-log': typeof AdminFormLogRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/merged': typeof AdminMergedRoute
  '/admin/rupture': typeof AdminRuptureRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/validations': typeof AdminValidationsRouteWithChildren
  '/company/$token': typeof CompanyTokenRoute
  '/student/$token': typeof StudentTokenRoute
  '/student/convention': typeof StudentConventionRoute
  '/student/merci': typeof StudentMerciRoute
  '/admin': typeof AdminIndexRoute
  '/company': typeof CompanyIndexRoute
  '/admin/companies/$id': typeof AdminCompaniesIdRoute
  '/admin/validations/$id': typeof AdminValidationsIdRoute
  '/admin/companies': typeof AdminCompaniesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/company': typeof CompanyRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/admin/attestation': typeof AdminAttestationRoute
  '/admin/companies': typeof AdminCompaniesRouteWithChildren
  '/admin/convention': typeof AdminConventionRoute
  '/admin/convention-tracking': typeof AdminConventionTrackingRoute
  '/admin/feuille-suivi': typeof AdminFeuilleSuiviRoute
  '/admin/form-log': typeof AdminFormLogRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/merged': typeof AdminMergedRoute
  '/admin/rupture': typeof AdminRuptureRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/validations': typeof AdminValidationsRouteWithChildren
  '/company/$token': typeof CompanyTokenRoute
  '/student/$token': typeof StudentTokenRoute
  '/student/convention': typeof StudentConventionRoute
  '/student/merci': typeof StudentMerciRoute
  '/admin/': typeof AdminIndexRoute
  '/company/': typeof CompanyIndexRoute
  '/admin/companies/$id': typeof AdminCompaniesIdRoute
  '/admin/validations/$id': typeof AdminValidationsIdRoute
  '/admin/companies/': typeof AdminCompaniesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/company'
    | '/student'
    | '/admin/attestation'
    | '/admin/companies'
    | '/admin/convention'
    | '/admin/convention-tracking'
    | '/admin/feuille-suivi'
    | '/admin/form-log'
    | '/admin/links'
    | '/admin/merged'
    | '/admin/rupture'
    | '/admin/students'
    | '/admin/validations'
    | '/company/$token'
    | '/student/$token'
    | '/student/convention'
    | '/student/merci'
    | '/admin/'
    | '/company/'
    | '/admin/companies/$id'
    | '/admin/validations/$id'
    | '/admin/companies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/student'
    | '/admin/attestation'
    | '/admin/convention'
    | '/admin/convention-tracking'
    | '/admin/feuille-suivi'
    | '/admin/form-log'
    | '/admin/links'
    | '/admin/merged'
    | '/admin/rupture'
    | '/admin/students'
    | '/admin/validations'
    | '/company/$token'
    | '/student/$token'
    | '/student/convention'
    | '/student/merci'
    | '/admin'
    | '/company'
    | '/admin/companies/$id'
    | '/admin/validations/$id'
    | '/admin/companies'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/company'
    | '/student'
    | '/admin/attestation'
    | '/admin/companies'
    | '/admin/convention'
    | '/admin/convention-tracking'
    | '/admin/feuille-suivi'
    | '/admin/form-log'
    | '/admin/links'
    | '/admin/merged'
    | '/admin/rupture'
    | '/admin/students'
    | '/admin/validations'
    | '/company/$token'
    | '/student/$token'
    | '/student/convention'
    | '/student/merci'
    | '/admin/'
    | '/company/'
    | '/admin/companies/$id'
    | '/admin/validations/$id'
    | '/admin/companies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CompanyRoute: typeof CompanyRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/': {
      id: '/company/'
      path: '/'
      fullPath: '/company/'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/merci': {
      id: '/student/merci'
      path: '/merci'
      fullPath: '/student/merci'
      preLoaderRoute: typeof StudentMerciRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/convention': {
      id: '/student/convention'
      path: '/convention'
      fullPath: '/student/convention'
      preLoaderRoute: typeof StudentConventionRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/$token': {
      id: '/student/$token'
      path: '/$token'
      fullPath: '/student/$token'
      preLoaderRoute: typeof StudentTokenRouteImport
      parentRoute: typeof StudentRoute
    }
    '/company/$token': {
      id: '/company/$token'
      path: '/$token'
      fullPath: '/company/$token'
      preLoaderRoute: typeof CompanyTokenRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/admin/validations': {
      id: '/admin/validations'
      path: '/validations'
      fullPath: '/admin/validations'
      preLoaderRoute: typeof AdminValidationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rupture': {
      id: '/admin/rupture'
      path: '/rupture'
      fullPath: '/admin/rupture'
      preLoaderRoute: typeof AdminRuptureRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merged': {
      id: '/admin/merged'
      path: '/merged'
      fullPath: '/admin/merged'
      preLoaderRoute: typeof AdminMergedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/links': {
      id: '/admin/links'
      path: '/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/form-log': {
      id: '/admin/form-log'
      path: '/form-log'
      fullPath: '/admin/form-log'
      preLoaderRoute: typeof AdminFormLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feuille-suivi': {
      id: '/admin/feuille-suivi'
      path: '/feuille-suivi'
      fullPath: '/admin/feuille-suivi'
      preLoaderRoute: typeof AdminFeuilleSuiviRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/convention-tracking': {
      id: '/admin/convention-tracking'
      path: '/convention-tracking'
      fullPath: '/admin/convention-tracking'
      preLoaderRoute: typeof AdminConventionTrackingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/convention': {
      id: '/admin/convention'
      path: '/convention'
      fullPath: '/admin/convention'
      preLoaderRoute: typeof AdminConventionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attestation': {
      id: '/admin/attestation'
      path: '/attestation'
      fullPath: '/admin/attestation'
      preLoaderRoute: typeof AdminAttestationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies/': {
      id: '/admin/companies/'
      path: '/'
      fullPath: '/admin/companies/'
      preLoaderRoute: typeof AdminCompaniesIndexRouteImport
      parentRoute: typeof AdminCompaniesRoute
    }
    '/admin/validations/$id': {
      id: '/admin/validations/$id'
      path: '/$id'
      fullPath: '/admin/validations/$id'
      preLoaderRoute: typeof AdminValidationsIdRouteImport
      parentRoute: typeof AdminValidationsRoute
    }
    '/admin/companies/$id': {
      id: '/admin/companies/$id'
      path: '/$id'
      fullPath: '/admin/companies/$id'
      preLoaderRoute: typeof AdminCompaniesIdRouteImport
      parentRoute: typeof AdminCompaniesRoute
    }
  }
}

interface AdminCompaniesRouteChildren {
  AdminCompaniesIdRoute: typeof AdminCompaniesIdRoute
  AdminCompaniesIndexRoute: typeof AdminCompaniesIndexRoute
}

const AdminCompaniesRouteChildren: AdminCompaniesRouteChildren = {
  AdminCompaniesIdRoute: AdminCompaniesIdRoute,
  AdminCompaniesIndexRoute: AdminCompaniesIndexRoute,
}

const AdminCompaniesRouteWithChildren = AdminCompaniesRoute._addFileChildren(
  AdminCompaniesRouteChildren,
)

interface AdminValidationsRouteChildren {
  AdminValidationsIdRoute: typeof AdminValidationsIdRoute
}

const AdminValidationsRouteChildren: AdminValidationsRouteChildren = {
  AdminValidationsIdRoute: AdminValidationsIdRoute,
}

const AdminValidationsRouteWithChildren =
  AdminValidationsRoute._addFileChildren(AdminValidationsRouteChildren)

interface AdminRouteChildren {
  AdminAttestationRoute: typeof AdminAttestationRoute
  AdminCompaniesRoute: typeof AdminCompaniesRouteWithChildren
  AdminConventionRoute: typeof AdminConventionRoute
  AdminConventionTrackingRoute: typeof AdminConventionTrackingRoute
  AdminFeuilleSuiviRoute: typeof AdminFeuilleSuiviRoute
  AdminFormLogRoute: typeof AdminFormLogRoute
  AdminLinksRoute: typeof AdminLinksRoute
  AdminMergedRoute: typeof AdminMergedRoute
  AdminRuptureRoute: typeof AdminRuptureRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminValidationsRoute: typeof AdminValidationsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAttestationRoute: AdminAttestationRoute,
  AdminCompaniesRoute: AdminCompaniesRouteWithChildren,
  AdminConventionRoute: AdminConventionRoute,
  AdminConventionTrackingRoute: AdminConventionTrackingRoute,
  AdminFeuilleSuiviRoute: AdminFeuilleSuiviRoute,
  AdminFormLogRoute: AdminFormLogRoute,
  AdminLinksRoute: AdminLinksRoute,
  AdminMergedRoute: AdminMergedRoute,
  AdminRuptureRoute: AdminRuptureRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminValidationsRoute: AdminValidationsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CompanyRouteChildren {
  CompanyTokenRoute: typeof CompanyTokenRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanyTokenRoute: CompanyTokenRoute,
  CompanyIndexRoute: CompanyIndexRoute,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

interface StudentRouteChildren {
  StudentTokenRoute: typeof StudentTokenRoute
  StudentConventionRoute: typeof StudentConventionRoute
  StudentMerciRoute: typeof StudentMerciRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentTokenRoute: StudentTokenRoute,
  StudentConventionRoute: StudentConventionRoute,
  StudentMerciRoute: StudentMerciRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CompanyRoute: CompanyRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
